jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '1.0.4'

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'

  - bash: ./build.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '1.0.4'

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'

  - bash: ./build.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

- job: Windows
  pool:
    vmImage: 'vs2017-win2017'

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '1.0.4'

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'

  - powershell: .\build.ps1
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
