jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 3
    matrix:
      DotNet10:
        dotnet_version: '1.0.4'
      DotNet11:
        dotnet_version: '1.1.4'
      DotNet20:
        dotnet_version: '2.1.401'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: $( dotnet_version )
  - bash: ./build.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      
# - job: macOS
#   pool:
#     vmImage: 'xcode9-macos10.13'

#   steps:
#   - bash: ./build.sh
#     env:
#       COREHOST_TRACE: 0
#       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#       DOTNET_CLI_TELEMETRY_OPTOUT: 1

# - job: Windows
#   pool:
#     vmImage: 'vs2017-win2017'

#   steps:
#   - powershell: .\build.ps1
#     env:
#       COREHOST_TRACE: 0
#       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#       DOTNET_CLI_TELEMETRY_OPTOUT: 1
